import js from '@eslint/js';
import json from '@eslint/json';
import eslintConfigPrettier from 'eslint-config-prettier';
import eslintPluginPrettier from 'eslint-plugin-prettier';
import globals from 'globals';

export default [
  {
    ignores: ['aws-sdk-js/**', 'dist/**', 'src-sdk/**', 'node_modules/**'],
  },
  {
    files: ['**/*.js'],
    ...js.configs.recommended,
    languageOptions: {
      ecmaVersion: 2018,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2017,
        ...globals.node,
      },
    },
    plugins: {
      prettier: eslintPluginPrettier,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...eslintConfigPrettier.rules,
      indent: ['error', 2, { SwitchCase: 1 }],
      'linebreak-style': ['error', 'unix'],
      quotes: ['error', 'single', { avoidEscape: true }],
      semi: ['error', 'always'],
      'prefer-arrow-callback': 'error',
      'no-console': 'off',
      curly: ['error', 'all'],
      'dot-location': ['error', 'property'],
      'prettier/prettier': ['error'],
    },
  },
  {
    files: ['test/*.js'],
    languageOptions: {
      globals: {
        ...globals.jest,
      },
    },
  },
  {
    files: ['src/*.js'],
    languageOptions: {
      globals: {
        AWS: 'readonly',
        // Google Apps Script globals
        AdSense: 'readonly',
        AdminDirectory: 'readonly',
        AdminGroupsMigration: 'readonly',
        AdminGroupsSettings: 'readonly',
        AdminLicenseManager: 'readonly',
        AdminReports: 'readonly',
        AdminReseller: 'readonly',
        Analytics: 'readonly',
        AnalyticsReporting: 'readonly',
        AppsActivity: 'readonly',
        BigQuery: 'readonly',
        Browser: 'readonly',
        CacheService: 'readonly',
        Calendar: 'readonly',
        CalendarApp: 'readonly',
        CardService: 'readonly',
        Charts: 'readonly',
        Classroom: 'readonly',
        ConferenceDataService: 'readonly',
        ContactsApp: 'readonly',
        ContentService: 'readonly',
        DataStudioApp: 'readonly',
        Docs: 'readonly',
        DocumentApp: 'readonly',
        DoubleClickCampaigns: 'readonly',
        Drive: 'readonly',
        DriveActivity: 'readonly',
        DriveApp: 'readonly',
        FormApp: 'readonly',
        FusionTables: 'readonly',
        Gmail: 'readonly',
        GmailApp: 'readonly',
        GoogleAppsScript: 'readonly',
        GroupsApp: 'readonly',
        HtmlService: 'readonly',
        Jdbc: 'readonly',
        LanguageApp: 'readonly',
        LinearOptimizationService: 'readonly',
        LockService: 'readonly',
        Logger: 'readonly',
        MailApp: 'readonly',
        Maps: 'readonly',
        MimeType: 'readonly',
        Mirror: 'readonly',
        People: 'readonly',
        PropertiesService: 'readonly',
        ScriptApp: 'readonly',
        Session: 'readonly',
        Sheets: 'readonly',
        ShoppingContent: 'readonly',
        SitesApp: 'readonly',
        Slides: 'readonly',
        SlidesApp: 'readonly',
        SpreadsheetApp: 'readonly',
        TagManager: 'readonly',
        Tasks: 'readonly',
        UrlFetchApp: 'readonly',
        Utilities: 'readonly',
        XmlService: 'readonly',
        YouTube: 'readonly',
        YouTubeAnalytics: 'readonly',
        YouTubeContentId: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'off',
      'no-undef': 'off',
    },
  },
  {
    files: ['**/*.json'],
    ignores: ['package-lock.json'],
    plugins: { json },
    language: 'json/json',
    rules: {
      'json/no-duplicate-keys': 'error',
    },
  },
];
